### ISSUE TITLE
Investigate to see if Cassandra 4.1.x backend works with 4.0 persistence & if not, how big are changes needed

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2609]
Since Cassandra 4.1.x has been released a while ago, it's probably worth checking how compatible our Cassandra 4.x backend is wrt this new version.

Related to earlier #2311.

**Comment by tatu-at-datastax** [comment]
Looks like there are source-incompatible changes in 4.1; it's not really a minor version upgrade from extensibility perspective:

```
[ERROR] /Users/tatusaloranta/git-datastax/stargate-v2/coordinator/persistence-cassandra-4.0/src/main/java/io/stargate/db/cassandra/impl/Cassandra40Persistence.java:[45,39] cannot find symbol
[ERROR]   symbol:   class LocalAwareExecutorService
[ERROR]   location: package org.apache.cassandra.concurrent
[ERROR] /Users/tatusaloranta/git-datastax/stargate-v2/coordinator/persistence-cassandra-4.0/src/main/java/io/stargate/db/cassandra/impl/Cassandra40Persistence.java:[124,11] cannot find symbol
[ERROR]   symbol:   class LocalAwareExecutorService
[ERROR]   location: class io.stargate.db.cassandra.impl.Cassandra40Persistence
[ERROR] /Users/tatusaloranta/git-datastax/stargate-v2/coordinator/persistence-cassandra-4.0/src/main/java/io/stargate/db/cassandra/impl/EventListenerWrapper.java:[8,43] no interface expected here
[ERROR] /Users/tatusaloranta/git-datastax/stargate-v2/coordinator/persistence-cassandra-4.0/src/main/java/io/stargate/db/cassandra/impl/SimpleCallbackMigrationListener.java:[13,56] no interface expected here
[ERROR] -> [Help 1]
```

**Comment by tatu-at-datastax** [comment]
Looking at https://fossies.org/diffs/apache-cassandra/4.0.7_vs_4.1.0/ here are some necessary changes for backend.

Changes needed:

* `LocalAwareExecutorService` renamed as `LocalAwareExecutorPlus`
* `SchemaChangeListener` became interface (from abstract class), was rewritten with full typing
     * Need to change "extends" to "implements" in 2 places as well as do other rewrite -- `io/stargate/db/cassandra/impl/EventListenerWrapper.java` and `io/stargate/db/cassandra/impl/SimpleCallbackMigrationListener.java`
